Models/Event.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace SportsManagementSystem.Models
{
    public class Event
    {
        [Display(Name = "Event ID")]
        [Key]
        public int EventId { get; set; }


        // Navigation Properties
        [Display(Name = "Game ID")]
        [ForeignKey("Game")]
        public int GameId { get; set; }
        public virtual Game Game { get; set; }


        [Display(Name = "Featured Event")]
        public string FeatureEvent { get; set; }
        [Required] public string Venue { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public DateTime Date { get; set; }

        [Required]
        [DataType(DataType.Time)]
        [Display(Name = "Start Time")]
        public DateTime StartTime { get; set; }

        [DataType(DataType.Time)]
        public DateTime EndTime { get; set; }

        [Required] public string Description { get; set; }
        [Display(Name = "World Record")]
        public string WorldRecord { get; set; }
    }
}

Controllers/EventOutcomesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SportsManagementSystem.Data;
using SportsManagementSystem.Models;

namespace SportsManagementSystem.Controllers
{
    [Authorize(Roles = "EventManager")]
    public class EventOutcomesController : Controller
    {
        private readonly SportsDbContext _context;

        public EventOutcomesController(SportsDbContext context)
        {
            _context = context;
        }

        // GET: EventOutcomes
        public async Task<IActionResult> Index()
        {
            var sportsDbContext = _context.EventOutcomes.Include(e => e.Competitor).Include(e => e.Event);
            return View(await sportsDbContext.ToListAsync());
        }

        // GET: EventOutcomes/Details/5
        public async Task<IActionResult> Details(int? Event_ID, int? Competitor_ID)
        {
            if (Event_ID == null || Competitor_ID == null)
            {
                return NotFound();
            }

            var eventOutcome = await _context.EventOutcomes
                .Include(e => e.Competitor)
                .Include(e => e.Event)
                .FirstOrDefaultAsync(m => m.EventId == Event_ID);
            if (eventOutcome == null)
            {
                return NotFound();
            }

            return View(eventOutcome);
        }

        // GET: EventOutcomes/Create
        public IActionResult Create()
        {
            ViewData["CompetitorId"] = new SelectList(_context.Competitors, "CompetitorId", "Name");
            ViewData["EventId"] = new SelectList(_context.Events, "EventId", "EventId");
            return View();
        }

        // POST: EventOutcomes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EventId,CompetitorId,Position")] EventOutcome eventOutcome)
        {
            if (ModelState.IsValid)
            {
                _context.Add(eventOutcome);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CompetitorId"] = new SelectList(_context.Competitors, "CompetitorId", "Name", eventOutcome.CompetitorId);
            ViewData["EventId"] = new SelectList(_context.Events, "EventId", "EventId", eventOutcome.EventId);
            return View(eventOutcome);
        }

        // GET: EventOutcomes/Delete/5
        public async Task<IActionResult> Delete(int? Event_ID, int? Competitor_ID)
        {
            if (Event_ID == null || Competitor_ID == null)
            {
                return NotFound();
            }

            var eventOutcome = await _context.EventOutcomes
                .Include(e => e.Competitor)
                .Include(e => e.Event)
                .FirstOrDefaultAsync(m => m.EventId == Event_ID);
            if (eventOutcome == null)
            {
                return NotFound();
            }

            return View(eventOutcome);
        }

        // POST: EventOutcomes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int Event_ID, int Competitor_ID)
        {
            var eventOutcome = await _context.EventOutcomes.FindAsync(Event_ID, Competitor_ID);
            _context.EventOutcomes.Remove(eventOutcome);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EventOutcomeExists(int? Event_ID, int? Competitor_ID)
        {
            return _context.EventOutcomes.Any(e => e.EventId == Event_ID) || _context.EventOutcomes.Any(e => e.CompetitorId == Competitor_ID);
        }
    }
}

Controllers/EventPhotoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SportsManagementSystem.Data;
using SportsManagementSystem.Models;

namespace SportsManagementSystem.Controllers
{
    [Authorize(Roles = "EventManager")]
    public class EventPhotoesController : Controller
    {
        private readonly SportsDbContext _context;

        public EventPhotoesController(SportsDbContext context)
        {
            _context = context;
        }

        // GET: EventPhotoes
        public async Task<IActionResult> Index()
        {
            var sportsDbContext = _context.EventPhotos.Include(e => e.Event);
            return View(await sportsDbContext.ToListAsync());
        }

        // GET: EventPhotoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventPhoto = await _context.EventPhotos
                .Include(e => e.Event)
                .FirstOrDefaultAsync(m => m.PhotoId == id);
            if (eventPhoto == null)
            {
                return NotFound();
            }

            return View(eventPhoto);
        }

        // GET: EventPhotoes/Create
        public IActionResult Create()
        {
            ViewData["EventId"] = new SelectList(_context.Events, "EventId", "EventId");
            return View();
        }

        // POST: EventPhotoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PhotoId,Photo,PhotoTags,EventId")] EventPhoto eventPhoto)
        {
            if (ModelState.IsValid)
            {
                _context.Add(eventPhoto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["EventId"] = new SelectList(_context.Events, "EventId", "EventId", eventPhoto.EventId);
            return View(eventPhoto);
        }

        // GET: EventPhotoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventPhoto = await _context.EventPhotos.FindAsync(id);
            if (eventPhoto == null)
            {
                return NotFound();
            }
            ViewData["EventId"] = new SelectList(_context.Events, "EventId", "EventId", eventPhoto.EventId);
            return View(eventPhoto);
        }

        // POST: EventPhotoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PhotoId,Photo,PhotoTags,EventId")] EventPhoto eventPhoto)
        {
            if (id != eventPhoto.PhotoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(eventPhoto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventPhotoExists(eventPhoto.PhotoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EventId"] = new SelectList(_context.Events, "EventId", "EventId", eventPhoto.EventId);
            return View(eventPhoto);
        }

        // GET: EventPhotoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventPhoto = await _context.EventPhotos
                .Include(e => e.Event)
                .FirstOrDefaultAsync(m => m.PhotoId == id);
            if (eventPhoto == null)
            {
                return NotFound();
            }

            return View(eventPhoto);
        }

        // POST: EventPhotoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var eventPhoto = await _context.EventPhotos.FindAsync(id);
            _context.EventPhotos.Remove(eventPhoto);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EventPhotoExists(int id)
        {
            return _context.EventPhotos.Any(e => e.PhotoId == id);
        }
    }
}

Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SportsManagementSystem.Data;
using SportsManagementSystem.Models;

namespace SportsManagementSystem.Controllers
{
    [Authorize(Roles = "EventManager")]
    public class EventsController : Controller
    {
        private readonly SportsDbContext _context;

        public EventsController(SportsDbContext context)
        {
            _context = context;
        }

        // GET: Events
        public async Task<IActionResult> Index()
        {
            var sportsDbContext = _context.Events.Include(c => c.Game);
            return View(await sportsDbContext.ToListAsync());
        }

        // GET: Events/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Events
                .Include(c => c.Game)
                .FirstOrDefaultAsync(m => m.EventId == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // GET: Events/Create
        public IActionResult Create()
        {
            ViewData["GameId"] = new SelectList(_context.Games, "GameId", "Code");
            return View();
        }

        // POST: Events/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EventId,FeatureEvent,Venue,Date,StartTime,EndTime,Description,WorldRecord,GameId")] Event @event)
        {
            if (ModelState.IsValid)
            {
                _context.Add(@event);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["GameId"] = new SelectList(_context.Games, "GameId", "Code", @event.GameId);
            return View(@event);
        }

        // GET: Events/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Events.FindAsync(id);
            if (@event == null)
            {
                return NotFound();
            }
            ViewData["GameId"] = new SelectList(_context.Games, "GameId", "Code", @event.GameId);
            return View(@event);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EventId,FeatureEvent,Venue,Date,StartTime,EndTime,Description,WorldRecord,GameId")] Event @event)
        {
            if (id != @event.EventId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@event);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventExists(@event.EventId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GameId"] = new SelectList(_context.Games, "GameId", "Code", @event.GameId);
            return View(@event);
        }

        // GET: Events/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Events
                .Include(c => c.Game)
                .FirstOrDefaultAsync(m => m.EventId == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // POST: Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var @event = await _context.Events.FindAsync(id);
            _context.Events.Remove(@event);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EventExists(int id)
        {
            return _context.Events.Any(e => e.EventId == id);
        }
    }
}

Views/Events/Create.cshtml
@model SportsManagementSystem.Models.Event

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Event</h4>
<hr />
<div class="row">
    <div class="col-8">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <label asp-for="GameId" class="control-label"></label>
                        <select asp-for="GameId" class="form-control" asp-items="ViewBag.GameId"></select>
                    </div>
                    <div class="form-group">
                        <label asp-for="FeatureEvent" class="control-label"></label>
                        <input asp-for="FeatureEvent" class="form-control" />
                        <span asp-validation-for="FeatureEvent" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Venue" class="control-label"></label>
                        <input asp-for="Venue" class="form-control" />
                        <span asp-validation-for="Venue" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Date" class="control-label"></label>
                        <input asp-for="Date" class="form-control" />
                        <span asp-validation-for="Date" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-3"></div>
                <div class="col">
                    <div class="form-group">
                        <label asp-for="StartTime" class="control-label"></label>
                        <input asp-for="StartTime" class="form-control" />
                        <span asp-validation-for="StartTime" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="EndTime" class="control-label"></label>
                        <input asp-for="EndTime" class="form-control" />
                        <span asp-validation-for="EndTime" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="WorldRecord" class="control-label"></label>
                        <input asp-for="WorldRecord" class="form-control" />
                        <span asp-validation-for="WorldRecord" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </div>
            <div class="row">
                <a class="btn btn-primary btn-sm" asp-action="Index"><i class="fas fa-undo-alt"></i> Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Events/Delete.cshtml
@model SportsManagementSystem.Models.Event

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Event</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Game)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Game.Code)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FeatureEvent)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FeatureEvent)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Venue)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Venue)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StartTime)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EndTime)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.WorldRecord)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.WorldRecord)
        </dd>
    </dl>

    <form asp-action="Delete">
        <div class="row">
            <div class="form-group">
                <input type="hidden" asp-for="EventId" />
                <input type="submit" value="Delete" class="btn btn-danger" />
            </div>
        </div>
    </form>
    <div class="row">
        <a class="btn btn-primary btn-sm" asp-action="Index"><i class="fas fa-undo-alt"></i> Back to List</a>
    </div>
</div>

Views/Events/Details.cshtml
@model SportsManagementSystem.Models.Event

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Event</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Game)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Game.Code)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FeatureEvent)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FeatureEvent)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Venue)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Venue)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StartTime)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EndTime)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.WorldRecord)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.WorldRecord)
        </dd>
    </dl>
</div>
<div class="row">
    <div class="form-group">
        <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model.EventId">Edit</a>
    </div>
</div>
<div class="row">
    <a class="btn btn-primary btn-sm" asp-action="Index"><i class="fas fa-undo-alt"></i> Back to List</a>
</div>

Views/Events/Edit.cshtml
@model SportsManagementSystem.Models.Event

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Event</h4>
<hr />
<div class="row">
    <div class="col-md-8">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="EventId" />
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <label asp-for="GameId" class="control-label"></label>
                        <select asp-for="GameId" class="form-control" asp-items="ViewBag.GameId"></select>
                    </div>
                    <div class="form-group">
                        <label asp-for="FeatureEvent" class="control-label"></label>
                        <input asp-for="FeatureEvent" class="form-control" />
                        <span asp-validation-for="FeatureEvent" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Venue" class="control-label"></label>
                        <input asp-for="Venue" class="form-control" />
                        <span asp-validation-for="Venue" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Date" class="control-label"></label>
                        <input asp-for="Date" class="form-control" />
                        <span asp-validation-for="Date" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-3"></div>
                <div class="col">
                    <div class="form-group">
                        <label asp-for="StartTime" class="control-label"></label>
                        <input asp-for="StartTime" class="form-control" />
                        <span asp-validation-for="StartTime" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="EndTime" class="control-label"></label>
                        <input asp-for="EndTime" class="form-control" />
                        <span asp-validation-for="EndTime" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="WorldRecord" class="control-label"></label>
                        <input asp-for="WorldRecord" class="form-control" />
                        <span asp-validation-for="WorldRecord" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </div>
            <div class="row">
                <a class="btn btn-primary btn-sm" asp-action="Index"><i class="fas fa-undo-alt"></i> Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Events/Index.cshtml
@model IEnumerable<SportsManagementSystem.Models.Event>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<div class="container">
    <div class="row">
        <div class="col-3">
            <p>
                <a class="btn btn-primary btn-sm" asp-action="Create"><i class="fas fa-plus-square"></i> New Event</a>
            </p>

        </div>
        <div class="col-3">
            <p>
                <a class="btn btn-primary btn-sm" asp-controller="EventOutcomes"><i class="fas fa-edit"></i> Edit Event Outcomes</a>
            </p>
        </div>
        <div class="col-3">
            <p>
                <a class="btn btn-primary btn-sm" asp-controller="EventPhotoes"><i class="fas fa-edit"></i> Edit Event Photos</a>
            </p>
        </div>
    </div>
    <div class="row">
        <table class="table">
            <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Game)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FeatureEvent)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Venue)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Date)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.StartTime)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.EndTime)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.WorldRecord)
                </th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Game.Code)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FeatureEvent)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Venue)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Date)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StartTime)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EndTime)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.WorldRecord)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.EventId">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.EventId">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.EventId">Delete</a>
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>
</div>