Controllers/EventPhotoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SportsManagementSystem.Data;
using SportsManagementSystem.Models;

namespace SportsManagementSystem.Controllers
{
    [Authorize(Roles = "EventManager")]
    public class EventPhotoesController : Controller
    {
        private readonly SportsDbContext _context;

        public EventPhotoesController(SportsDbContext context)
        {
            _context = context;
        }

        // GET: EventPhotoes
        public async Task<IActionResult> Index()
        {
            var sportsDbContext = _context.EventPhotos.Include(e => e.Event);
            return View(await sportsDbContext.ToListAsync());
        }

        // GET: EventPhotoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventPhoto = await _context.EventPhotos
                .Include(e => e.Event)
                .FirstOrDefaultAsync(m => m.PhotoId == id);
            if (eventPhoto == null)
            {
                return NotFound();
            }

            return View(eventPhoto);
        }

        // GET: EventPhotoes/Create
        public IActionResult Create()
        {
            ViewData["EventId"] = new SelectList(_context.Events, "EventId", "EventId");
            return View();
        }

        // POST: EventPhotoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PhotoId,Photo,PhotoTags,EventId")] EventPhoto eventPhoto)
        {
            if (ModelState.IsValid)
            {
                _context.Add(eventPhoto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["EventId"] = new SelectList(_context.Events, "EventId", "EventId", eventPhoto.EventId);
            return View(eventPhoto);
        }

        // GET: EventPhotoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventPhoto = await _context.EventPhotos.FindAsync(id);
            if (eventPhoto == null)
            {
                return NotFound();
            }
            ViewData["EventId"] = new SelectList(_context.Events, "EventId", "EventId", eventPhoto.EventId);
            return View(eventPhoto);
        }

        // POST: EventPhotoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PhotoId,Photo,PhotoTags,EventId")] EventPhoto eventPhoto)
        {
            if (id != eventPhoto.PhotoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(eventPhoto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventPhotoExists(eventPhoto.PhotoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EventId"] = new SelectList(_context.Events, "EventId", "EventId", eventPhoto.EventId);
            return View(eventPhoto);
        }

        // GET: EventPhotoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventPhoto = await _context.EventPhotos
                .Include(e => e.Event)
                .FirstOrDefaultAsync(m => m.PhotoId == id);
            if (eventPhoto == null)
            {
                return NotFound();
            }

            return View(eventPhoto);
        }

        // POST: EventPhotoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var eventPhoto = await _context.EventPhotos.FindAsync(id);
            _context.EventPhotos.Remove(eventPhoto);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EventPhotoExists(int id)
        {
            return _context.EventPhotos.Any(e => e.PhotoId == id);
        }
    }
}

Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SportsManagementSystem.Data;
using SportsManagementSystem.Models;

namespace SportsManagementSystem.Controllers
{
    [Authorize(Roles = "EventManager")]
    public class ReportsController : Controller
    {
        private readonly SportsDbContext _context;

        public ReportsController(SportsDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Events.ToListAsync());
        }


        public class Leaderboard
        {
            public Dictionary<string, int> Countries = new Dictionary<string, int>();
        }

        public async Task<IActionResult> TallyList()
        {
            var outcomes = await _context.EventOutcomes.ToListAsync();
            var competitors = await _context.Competitors.ToListAsync();

            Leaderboard board = new Leaderboard();

            foreach (var comp in competitors)
            {
                if (!board.Countries.ContainsKey(comp.Country))
                {
                    board.Countries.Add(comp.Country, 0);
                }
            }

            foreach (var outcome in outcomes)
            {
                if (outcome.Medal == "Gold" || outcome.Medal == "Silver" || outcome.Medal == "Bronze")
                {
                    foreach (var comp in competitors)
                    {
                        if (comp.CompetitorId == outcome.CompetitorId)
                        {
                            board.Countries[comp.Country]++;
                        }
                    }
                }
            }

            var sortedList = board.Countries.ToList();
            sortedList.Sort((pair1, pair2) => pair2.Value.CompareTo(pair1.Value));

            return View(sortedList);
        }

        public async Task<IActionResult> Search(string searchTerm)
        {
            var query =
                from s in _context.EventPhotos
                select s;

            if (!String.IsNullOrEmpty(searchTerm))
            {
                query = query.Where(s => s.PhotoTags.Contains(searchTerm));
            }

            return View(await query.ToListAsync());
        }
    }
}

Views/Reports/Index.cshtml
@model IEnumerable<SportsManagementSystem.Models.Event>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Reports Home</h1>

<div class="container">
    <div class="row">
        <div class="col-3">
            <p>
                <a class="btn btn-primary btn-sm" asp-action="TallyList"><i class="fas fa-list-ol"></i> Leaderboard</a>
            </p>
        </div>
        <div class="col-3">
            <p>
                <a class="btn btn-primary btn-sm" asp-action="Search">Search</a>
            </p>
        </div>
    </div>
    <div class="row">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.GameId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.FeatureEvent)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Venue)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Date)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.StartTime)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.EndTime)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Description)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.WorldRecord)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.GameId)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FeatureEvent)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Venue)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Date)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.StartTime)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.EndTime)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.WorldRecord)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Views/Reports/Search.cshtml
@model List<EventPhoto>

@{
    ViewBag.Title = "Search";
    Layout = "_Layout";
}

<h1>Search</h1>
<div class="container">
    <form asp-controller="Reports" asp-action="Search">
        <div class="row">
            <div class="col-6">
                Photo Tag:<input class="form-control" type="text" name="searchTerm"/></div>
            <div class="col-6">
                <input class="btn btn-primary" type="submit" value="Search"/></div>
        </div>
    </form>
</div>
<div class="container">
    <div class="row">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Photo
                    </th>
                    <th>
                        Tags
                    </th>
                    <th>
                        Event ID
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Photo)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PhotoTags)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Event.EventId)
                        </td>
                        <td>
                            <a asp-controller="EventPhotoes" asp-action="Edit" asp-route-id="@item.PhotoId">Edit</a> |
                            <a asp-controller="EventPhotoes" asp-action="Details" asp-route-id="@item.PhotoId">Details</a> |
                            <a asp-controller="EventPhotoes" asp-action="Delete" asp-route-id="@item.PhotoId">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Views/Reports/TallyList.cshtml
@model List<KeyValuePair<string, int>>

@{
    ViewData["Title"] = "Tally List";
    Layout = "_Layout";
}

<div class="container">
    <div class="row">
        <div class="col-3">
            <p>
                <a class="btn btn-primary btn-sm" asp-action="Index"><i class="fas fa-undo-alt"></i> Back to Reports</a>
            </p>
        </div>
    </div>
    <div class="row">
        <table class="table">
            <thead>
            <tr>
                <th>
                    Position
                </th>
                <th>
                    Countries
                </th>
                <th>
                    Medals
                </th>
            </tr>
            </thead>
            <tbody>
            @for (int i = 0; i < Model.Count; i++)
            {
                <tr>
                    <td>
                        @(i + 1)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model[i].Key)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model[i].Value)
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>
</div>