Models/Competitor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Security.AccessControl;
using System.Threading.Tasks;

namespace SportsManagementSystem.Models
{
    public enum Salutation
    {
        Mr, Mrs, Miss
    }
    
    public class Competitor
    {
        [Display(Name = "Competitor ID")]
        [Key]
        public int CompetitorId { get; set; }
        [DisplayFormat(NullDisplayText = "No Salutation")]
        public Salutation? Salutation { get; set; }
        [Required] public string Name { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = "Date of Birth")]
        public DateTime Dob { get; set; }
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        public string Description { get; set; }
        [Required] public string Country { get; set; }
        [Required] public string Gender { get; set; }
        [Display(Name = "Contact Number")]
        public string ContactNo { get; set; }

        public string Website { get; set; }
        public string Photo { get; set; }

        // Navigation Properties
        public virtual ICollection<CompetitorGames> CompetitorGames { get; set; }
    }
}

Controllers/CompetitorGamesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SportsManagementSystem.Data;
using SportsManagementSystem.Models;

namespace SportsManagementSystem.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CompetitorGamesController : Controller
    {
        private readonly SportsDbContext _context;

        public CompetitorGamesController(SportsDbContext context)
        {
            _context = context;
        }

        // GET: CompetitorGames
        public async Task<IActionResult> Index()
        {
            var sportsDbContext = _context.CompetitorGames.Include(c => c.Competitor).Include(c => c.Game);
            return View(await sportsDbContext.ToListAsync());
        }

        // GET: CompetitorGames/Details/5
        public async Task<IActionResult> Details(int? Game_ID, int? Competitor_ID)
        {
            if (Game_ID == null || Competitor_ID == null)
            {
                return NotFound();
            }

            var competitorGames = await _context.CompetitorGames
                .Include(c => c.Competitor)
                .Include(c => c.Game)
                .FirstOrDefaultAsync(m => m.CompetitorId == Competitor_ID);
            if (competitorGames == null)
            {
                return NotFound();
            }

            return View(competitorGames);
        }

        // GET: CompetitorGames/Create
        public IActionResult Create()
        {
            ViewData["CompetitorId"] = new SelectList(_context.Competitors, "CompetitorId", "Name");
            ViewData["GameId"] = new SelectList(_context.Games, "GameId", "Code");
            return View();
        }

        // POST: CompetitorGames/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CompetitorId,GameId")] CompetitorGames competitorGames)
        {
            if (ModelState.IsValid)
            {
                _context.Add(competitorGames);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CompetitorId"] = new SelectList(_context.Competitors, "CompetitorId", "Name", competitorGames.CompetitorId);
            ViewData["GameId"] = new SelectList(_context.Games, "GameId", "Code", competitorGames.GameId);
            return View(competitorGames);
        }

        // GET: CompetitorGames/Edit/5
        public async Task<IActionResult> Edit(int? Game_ID, int? Competitor_ID)
        {
            if (Game_ID == null || Competitor_ID == null)
            {
                return NotFound();
            }

            var competitorGames = await _context.CompetitorGames.FindAsync(Competitor_ID, Game_ID);
            if (competitorGames == null)
            {
                return NotFound();
            }
            ViewData["CompetitorId"] = new SelectList(_context.Competitors, "CompetitorId", "Name", competitorGames.CompetitorId);
            ViewData["GameId"] = new SelectList(_context.Games, "GameId", "Code", competitorGames.GameId);
            return View(competitorGames);
        }

        // POST: CompetitorGames/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? Game_ID, int? Competitor_ID, [Bind("CompetitorId,GameId")] CompetitorGames competitorGames)
        {
            if (Competitor_ID != competitorGames.CompetitorId || Game_ID != competitorGames.GameId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(competitorGames);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompetitorGamesExists(competitorGames.GameId, competitorGames.CompetitorId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            ViewData["CompetitorId"] = new SelectList(_context.Competitors, "CompetitorId", "Name", competitorGames.CompetitorId);
            ViewData["GameId"] = new SelectList(_context.Games, "GameId", "Code", competitorGames.GameId);
            return View(competitorGames);
        }

        private bool CompetitorGamesExists(int? Game_ID, int? Competitor_ID)
        {
            return _context.CompetitorGames.Any(e => e.CompetitorId == Competitor_ID) && _context.CompetitorGames.Any(e => e.GameId == Game_ID);
        }
    }
}

Controllers/CompetitorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SportsManagementSystem.Data;
using SportsManagementSystem.Models;

namespace SportsManagementSystem.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CompetitorsController : Controller
    {
        private readonly SportsDbContext _context;

        public CompetitorsController(SportsDbContext context)
        {
            _context = context;
        }

        // GET: Competitors
        public async Task<IActionResult> Index()
        {
            return View(await _context.Competitors.ToListAsync());
        }

        // GET: Competitors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var competitor = await _context.Competitors
                .FirstOrDefaultAsync(m => m.CompetitorId == id);
            if (competitor == null)
            {
                return NotFound();
            }

            return View(competitor);
        }

        // GET: Competitors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Competitors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CompetitorId,Salutation,Name,Dob,Email,Description,Country,Gender,ContactNo,Website,Photo")] Competitor competitor)
        {
            if (ModelState.IsValid)
            {
                _context.Add(competitor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(competitor);
        }

        // GET: Competitors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var competitor = await _context.Competitors.FindAsync(id);
            if (competitor == null)
            {
                return NotFound();
            }
            return View(competitor);
        }

        // POST: Competitors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CompetitorId,Salutation,Name,Dob,Email,Description,Country,Gender,ContactNo,Website,Photo")] Competitor competitor)
        {
            if (id != competitor.CompetitorId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(competitor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompetitorExists(competitor.CompetitorId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(competitor);
        }

        // GET: Competitors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var competitor = await _context.Competitors
                .FirstOrDefaultAsync(m => m.CompetitorId == id);
            if (competitor == null)
            {
                return NotFound();
            }

            return View(competitor);
        }

        // POST: Competitors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var competitor = await _context.Competitors.FindAsync(id);
            _context.Competitors.Remove(competitor);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CompetitorExists(int id)
        {
            return _context.Competitors.Any(e => e.CompetitorId == id);
        }
    }
}

Views/Competitors/Create.cshtml
@model SportsManagementSystem.Models.Competitor

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Competitor</h4>
<hr />
<div class="row">
    <div class="col-8">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <label asp-for="Salutation" class="control-label"></label>
                        <select class="form-control" asp-for="Salutation" asp-items="Html.GetEnumSelectList<Salutation>()">
                            <option selected="selected" value="">Please Select</option>
                        </select>
                        <span asp-validation-for="Salutation" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Dob" class="control-label"></label>
                        <input asp-for="Dob" class="form-control" />
                        <span asp-validation-for="Dob" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-3"></div>
                <div class="col">
                    <div class="form-group">
                        <label asp-for="Country" class="control-label"></label>
                        <input asp-for="Country" class="form-control" />
                        <span asp-validation-for="Country" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Gender" class="control-label"></label>
                        <input asp-for="Gender" class="form-control" />
                        <span asp-validation-for="Gender" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ContactNo" class="control-label"></label>
                        <input asp-for="ContactNo" class="form-control" />
                        <span asp-validation-for="ContactNo" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Website" class="control-label"></label>
                        <input asp-for="Website" class="form-control" />
                        <span asp-validation-for="Website" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Photo" class="control-label"></label>
                        <input asp-for="Photo" class="form-control" />
                        <span asp-validation-for="Photo" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </div>
            <div class="row">
                <a class="btn btn-primary btn-sm" asp-action="Index"><i class="fas fa-undo-alt"></i> Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Competitors/Delete.cshtml
@model SportsManagementSystem.Models.Competitor

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Competitor</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salutation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salutation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dob)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dob)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContactNo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContactNo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Website)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Website)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Photo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Photo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="row">
            <div class="form-group">
                <input type="hidden" asp-for="CompetitorId"/>
                <input type="submit" value="Delete" class="btn btn-danger"/>
            </div>
        </div>
    </form>
    <div class="row">
        <a class="btn btn-primary btn-sm" asp-action="Index"><i class="fas fa-undo-alt"></i> Back to List</a>
    </div>
</div>

Views/Competitors/Details.cshtml
@model SportsManagementSystem.Models.Competitor

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Competitor</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salutation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salutation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dob)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dob)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContactNo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContactNo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Website)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Website)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Photo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Photo)
        </dd>
    </dl>
</div>
<div class="row">
    <div class="form-group">
        <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model.CompetitorId">Edit</a>
    </div>
</div>
<div class="row">
    <a class="btn btn-primary btn-sm" asp-action="Index"><i class="fas fa-undo-alt"></i> Back to List</a>
</div>

Views/Competitors/Edit.cshtml
@model SportsManagementSystem.Models.Competitor

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Competitor</h4>
<hr />
<div class="row">
    <div class="col-md-8">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="col">
                    <input type="hidden" asp-for="CompetitorId" />
                    <div class="form-group">
                        <label asp-for="Salutation" class="control-label"></label>
                        <select class="form-control" asp-for="Salutation" asp-items="Html.GetEnumSelectList<Salutation>()">
                            <option selected="selected" value="">@ViewData.Model.Salutation</option>
                        </select>
                        <span asp-validation-for="Salutation" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Dob" class="control-label"></label>
                        <input asp-for="Dob" class="form-control" />
                        <span asp-validation-for="Dob" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-3"></div>
                <div class="col">
                    <div class="form-group">
                        <label asp-for="Country" class="control-label"></label>
                        <input asp-for="Country" class="form-control" />
                        <span asp-validation-for="Country" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Gender" class="control-label"></label>
                        <input asp-for="Gender" class="form-control" />
                        <span asp-validation-for="Gender" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ContactNo" class="control-label"></label>
                        <input asp-for="ContactNo" class="form-control" />
                        <span asp-validation-for="ContactNo" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Website" class="control-label"></label>
                        <input asp-for="Website" class="form-control" />
                        <span asp-validation-for="Website" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Photo" class="control-label"></label>
                        <input asp-for="Photo" class="form-control" />
                        <span asp-validation-for="Photo" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </div>
            <div class="row">
                <a class="btn btn-primary btn-sm" asp-action="Index"><i class="fas fa-undo-alt"></i> Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Competitors/Index.cshtml
@model IEnumerable<SportsManagementSystem.Models.Competitor>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<div class="container">
    <div class="row">
        <div class="col-3">
            <p>
                <a class="btn btn-primary btn-sm"asp-action="Create"><i class="fas fa-plus-square"></i> New Competitor</a>
            </p>
        </div>
        <div class="col-3">
            <p>
                <a class="btn btn-primary btn-sm" asp-controller="CompetitorGames"><i class="fas fa-edit"></i> Edit Competitor Games</a>
            </p>
        </div>
    </div>
    <div class="row">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Salutation)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Dob)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Email)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Description)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Country)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Gender)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ContactNo)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Website)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Photo)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Salutation)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Dob)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Email)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Country)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Gender)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ContactNo)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Website)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Photo)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.CompetitorId">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.CompetitorId">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.CompetitorId">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>