Models/EventOutcome.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Security.AccessControl;
using System.Threading.Tasks;

namespace SportsManagementSystem.Models
{

    public class EventOutcome
    {
        [ForeignKey("Event")]
        public int EventId { get; set; }
        public virtual Event Event { get; set; }
        [ForeignKey("Competitor")]
        [Display(Name = "Competitor ID")]
        public int CompetitorId { get; set; }
        public virtual Competitor Competitor { get; set; }
        [Required]
        public int Position { get; set; }

        public string Medal
        {
            get
            {
                if (Position == 1)
                {
                    return "Gold";
                }
                else if (Position == 2)
                {
                    return "Silver";
                }
                else if (Position == 3)
                {
                    return "Bronze";
                }
                else
                {
                    return null;
                }
            }
        }
    }
}

Controllers/EventOutcomesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SportsManagementSystem.Data;
using SportsManagementSystem.Models;

namespace SportsManagementSystem.Controllers
{
    [Authorize(Roles = "EventManager")]
    public class EventOutcomesController : Controller
    {
        private readonly SportsDbContext _context;

        public EventOutcomesController(SportsDbContext context)
        {
            _context = context;
        }

        // GET: EventOutcomes
        public async Task<IActionResult> Index()
        {
            var sportsDbContext = _context.EventOutcomes.Include(e => e.Competitor).Include(e => e.Event);
            return View(await sportsDbContext.ToListAsync());
        }

        // GET: EventOutcomes/Details/5
        public async Task<IActionResult> Details(int? Event_ID, int? Competitor_ID)
        {
            if (Event_ID == null || Competitor_ID == null)
            {
                return NotFound();
            }

            var eventOutcome = await _context.EventOutcomes
                .Include(e => e.Competitor)
                .Include(e => e.Event)
                .FirstOrDefaultAsync(m => m.EventId == Event_ID);
            if (eventOutcome == null)
            {
                return NotFound();
            }

            return View(eventOutcome);
        }

        // GET: EventOutcomes/Create
        public IActionResult Create()
        {
            ViewData["CompetitorId"] = new SelectList(_context.Competitors, "CompetitorId", "Name");
            ViewData["EventId"] = new SelectList(_context.Events, "EventId", "EventId");
            return View();
        }

        // POST: EventOutcomes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EventId,CompetitorId,Position")] EventOutcome eventOutcome)
        {
            if (ModelState.IsValid)
            {
                _context.Add(eventOutcome);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CompetitorId"] = new SelectList(_context.Competitors, "CompetitorId", "Name", eventOutcome.CompetitorId);
            ViewData["EventId"] = new SelectList(_context.Events, "EventId", "EventId", eventOutcome.EventId);
            return View(eventOutcome);
        }

        // GET: EventOutcomes/Delete/5
        public async Task<IActionResult> Delete(int? Event_ID, int? Competitor_ID)
        {
            if (Event_ID == null || Competitor_ID == null)
            {
                return NotFound();
            }

            var eventOutcome = await _context.EventOutcomes
                .Include(e => e.Competitor)
                .Include(e => e.Event)
                .FirstOrDefaultAsync(m => m.EventId == Event_ID);
            if (eventOutcome == null)
            {
                return NotFound();
            }

            return View(eventOutcome);
        }

        // POST: EventOutcomes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int Event_ID, int Competitor_ID)
        {
            var eventOutcome = await _context.EventOutcomes.FindAsync(Event_ID, Competitor_ID);
            _context.EventOutcomes.Remove(eventOutcome);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EventOutcomeExists(int? Event_ID, int? Competitor_ID)
        {
            return _context.EventOutcomes.Any(e => e.EventId == Event_ID) || _context.EventOutcomes.Any(e => e.CompetitorId == Competitor_ID);
        }
    }
}

Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SportsManagementSystem.Data;
using SportsManagementSystem.Models;

namespace SportsManagementSystem.Controllers
{
    [Authorize(Roles = "EventManager")]
    public class EventsController : Controller
    {
        private readonly SportsDbContext _context;

        public EventsController(SportsDbContext context)
        {
            _context = context;
        }

        // GET: Events
        public async Task<IActionResult> Index()
        {
            var sportsDbContext = _context.Events.Include(c => c.Game);
            return View(await sportsDbContext.ToListAsync());
        }

        // GET: Events/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Events
                .Include(c => c.Game)
                .FirstOrDefaultAsync(m => m.EventId == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // GET: Events/Create
        public IActionResult Create()
        {
            ViewData["GameId"] = new SelectList(_context.Games, "GameId", "Code");
            return View();
        }

        // POST: Events/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EventId,FeatureEvent,Venue,Date,StartTime,EndTime,Description,WorldRecord,GameId")] Event @event)
        {
            if (ModelState.IsValid)
            {
                _context.Add(@event);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["GameId"] = new SelectList(_context.Games, "GameId", "Code", @event.GameId);
            return View(@event);
        }

        // GET: Events/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Events.FindAsync(id);
            if (@event == null)
            {
                return NotFound();
            }
            ViewData["GameId"] = new SelectList(_context.Games, "GameId", "Code", @event.GameId);
            return View(@event);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EventId,FeatureEvent,Venue,Date,StartTime,EndTime,Description,WorldRecord,GameId")] Event @event)
        {
            if (id != @event.EventId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@event);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventExists(@event.EventId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GameId"] = new SelectList(_context.Games, "GameId", "Code", @event.GameId);
            return View(@event);
        }

        // GET: Events/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Events
                .Include(c => c.Game)
                .FirstOrDefaultAsync(m => m.EventId == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // POST: Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var @event = await _context.Events.FindAsync(id);
            _context.Events.Remove(@event);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EventExists(int id)
        {
            return _context.Events.Any(e => e.EventId == id);
        }
    }
}

Views/EventOutcomes/Create.cshtml
@model SportsManagementSystem.Models.EventOutcome

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>EventOutcome</h4>
<hr />
<div class="row">
    <div class="col-8">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EventId" class="control-label"></label>
                <select asp-for="EventId" class="form-control" asp-items="ViewBag.EventId"></select>
            </div>
            <div class="form-group">
                <label asp-for="CompetitorId" class="control-label"></label>
                <select asp-for="CompetitorId" class="form-control" asp-items="ViewBag.CompetitorId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Position" class="control-label"></label>
                <input asp-for="Position" class="form-control" />
                <span asp-validation-for="Position" class="text-danger"></span>
            </div>
            <div class="row">
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </div>
            <div class="row">
                <a class="btn btn-primary btn-sm" asp-action="Index"><i class="fas fa-undo-alt"></i> Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/EventOutcomes/Delete.cshtml
@model SportsManagementSystem.Models.EventOutcome

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>EventOutcome</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Event)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Event.EventId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Competitor)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Competitor.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Position)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Position)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Medal)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Medal)
        </dd>
    </dl>

    <form asp-action="Delete">
        <div class="row">
            <div class="form-group">
                <input type="hidden" asp-for="CompetitorId" />
                <input type="submit" value="Delete" class="btn btn-danger" />
            </div>
        </div>
    </form>
    <div class="row">
        <a class="btn btn-primary btn-sm" asp-action="Index"><i class="fas fa-undo-alt"></i> Back to List</a>
    </div>
</div>

Views/EventOutcomes/Details.cshtml
@model SportsManagementSystem.Models.EventOutcome

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>EventOutcome</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Event)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Event.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Competitor)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Competitor.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Position)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Position)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Medal)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Medal)
        </dd>
    </dl>
</div>
<div class="row">
    <a class="btn btn-primary btn-sm" asp-action="Index"><i class="fas fa-undo-alt"></i> Back to List</a>
</div>

Views/EventOutcomes/Index.cshtml
@model IEnumerable<SportsManagementSystem.Models.EventOutcome>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<div class="container">
    <div class="row">
        <div class="col-3">
            <p>
                <a class="btn btn-primary btn-sm" asp-controller="Events"><i class="fas fa-undo-alt"></i> Back to Event List</a>
            </p>
        </div>
        <div class="col-3">
            <p>
                <a class="btn btn-primary btn-sm" asp-action="Create"><i class="fas fa-plus-square"></i> New Event Outcome</a>
            </p>

        </div>
    </div>
    <div class="row">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Event)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Competitor)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Position)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Medal)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            @foreach (var item in Model) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Event.EventId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Competitor.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Position)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Medal)
                    </td>
                    <td>
                        @Html.ActionLink("Details", "Details", new { Event_ID = item.EventId, Competitor_ID = item.CompetitorId }) |
                        @Html.ActionLink("Delete", "Delete", new { Event_ID = item.EventId, Competitor_ID = item.CompetitorId })
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>
</div>